on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * *"

name: Build lightGBM

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - run: |
          git clone --recursive https://github.com/microsoft/LightGBM
          cd LightGBM
          Rscript build_r.R
