on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * *"

name: Build lightGBM

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        r: ["3.6", "4.0"]
    runs-on: ${{ matrix.os }} 
    name: ${{ matrix.os }} ${{ matrix.r }}
    timeout-minutes: 20
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@master
      - run: |
          brew install libomp
      - run: |
          Rscript -e 'install.packages(c("data.table", "R6", "jsonlite"))'
      - run: |
          git clone --recursive https://github.com/microsoft/LightGBM
          cd LightGBM
          Rscript build_r.R --skip-install
      - run: | 
          export CXX=g++-9 CC=gcc-9
          R CMD INSTALL --build $(find . -name "*.tar.gz")
      - name: Test installation
        run: |
          library(lightgbm)
          data(agaricus.train, package='lightgbm')
          train <- agaricus.train
          dtrain <- lgb.Dataset(train$data, label=train$label)
          params <- list(objective="regression", metric="l2")
          model <- lgb.cv(params, dtrain, 10, nfold=5, min_data=1, learning_rate=1, early_stopping_rounds=10)
        shell: Rscript {0}
      - run: |
          mkdir ${{runner.workspace}}/artifacts
          find  . -name '*.tgz' -exec cp '{}' ${{runner.workspace}}/artifacts/ ";"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{runner.os}}
          path: ${{runner.workspace}}/artifacts
      - name: upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.tgz'
          tag: macos-r-${{ matrix.r }}
          overwrite: true
          file_glob: true
  windows:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        r: ["3.6", "4.0"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.r }}
    timeout-minutes: 20
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@master
      - run: |
          Rscript -e "install.packages(c('data.table', 'R6', 'jsonlite'))"
      - run: |
          git clone --recursive https://github.com/microsoft/LightGBM
          cd LightGBM
          Rscript build_r.R --skip-install
      - run: | 
          install.packages("pkgbuild")
          setwd("./LightGBM/")
          file <- list.files(pattern = ".tar.gz")
          out <- pkgbuild::build(file, binary = TRUE, args = "--no-multiarch")
          install.packages(out, repos = NULL, type = "win.binary")
        shell: Rscript {0}
      - name: Test installation
        run: |
          library(lightgbm)
          data(agaricus.train, package='lightgbm')
          train <- agaricus.train
          dtrain <- lgb.Dataset(train$data, label=train$label)
          params <- list(objective="regression", metric="l2")
          model <- lgb.cv(params, dtrain, 10, nfold=5, min_data=1, learning_rate=1, early_stopping_rounds=10)
        shell: Rscript {0}
      - name: upload
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'LightGBM/*.zip'
          tag: windows-r-$${ matrix.r }}
          overwrite: true
          file_glob: true          
  
