on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * *"

name: Build lightGBM

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - run: |
          brew install libomp
      - run: |
          Rscript -e 'install.packages(c("data.table", "R6", "jsonlite"))'
      - run: |
          git clone --recursive https://github.com/microsoft/LightGBM
          cd LightGBM
          Rscript build_r.R --skip-install
      - run: | 
          export CXX=g++-9 CC=gcc-9
          R CMD INSTALL --build $(find . -name "*.tar.gz")
      - name: Test installation
        run: |
          library(lightgbm)
          data(agaricus.train, package='lightgbm')
          train <- agaricus.train
          dtrain <- lgb.Dataset(train$data, label=train$label)
          params <- list(objective="regression", metric="l2")
          model <- lgb.cv(params, dtrain, 10, nfold=5, min_data=1, learning_rate=1, early_stopping_rounds=10)
        shell: Rscript {0}
      - run: |
          mkdir ${{runner.workspace}}/artifacts
          find  . -name '*.tgz' -exec cp '{}' ${{runner.workspace}}/artifacts/ ";"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{runner.os}}
          path: ${{runner.workspace}}/artifacts
      - uses: csexton/release-asset-action@v2
        with:
          pattern: "*.tgz"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: https://uploads.github.com/repos/curso-r/lightgbm-build/releases/1/assets
        
          
